### ISSUE TITLE
fwrite(): send of 2 bytes failed with errno=32 Broken pipe

### ISSUE THREAD

**Issue by clarkk** [arthurkushman/php-wss#18]
Often I get this error

```
fwrite(): send of 2 bytes failed with errno=32 Broken pipe /var/www/.../php/class/third-party/php-wss/Components/Connection.php(32)
#0 [internal function]: {closure}(8, 'fwrite(): send ...', '/var/www/...', 32, Array)
#1 /var/www/.../php/class/third-party/php-wss/Components/Connection.php(32): fwrite(Resource id #27, '\x88\x00')
#2 /var/www/.../php/class/Websocket.php(102): WSSC\Components\Connection->close()
#3 /var/www/.../php/class/third-party/php-wss/WebSocketServer.php(195): ServerHandler->onClose(Object(WSSC\Components\Connection))
#4 /var/www/.../php/class/third-party/php-wss/WebSocketServer.php(145): WSSC\WebSocketServer->messagesWorker(Array)
#5 /var/www/.../php/class/third-party/php-wss/WebSocketServer.php(100): WSSC\WebSocketServer->looping(Resource id #25)
#6 /var/www/.../php/class/third-party/php-wss/WebSocketServer.php(75): WSSC\WebSocketServer->eventLoop(Resource id #25)
#7 /var/www/.../public/websocket/index.php(31): WSSC\WebSocketServer->run()
#8 {main}
```

**Comment by arthurkushman** [comment]
It looks like server is trying to write to a connection that has been closed on the client side.

**Comment by clarkk** [comment]
https://github.com/arthurkushman/php-wss/issues/19
