### ISSUE TITLE
Trying to access array offset on value of type bool 

### ISSUE THREAD

**Issue by jeankassio** [arthurkushman/php-wss#69]
```
[21-Jul-2022 07:45:28 America/Sao_Paulo] PHP Warning:  Trying to access array offset on value of type bool in /home/admin/web/socket.nfxtrade.com/public_html/vendor/arthurkushman/php-wss/src/WebSocketServer.php on line 238
[21-Jul-2022 07:45:28 America/Sao_Paulo] PHP Warning:  Trying to access array offset on value of type bool in /home/admin/web/socket.nfxtrade.com/public_html/vendor/arthurkushman/php-wss/src/WebSocketServer.php on line 239
[21-Jul-2022 07:45:28 America/Sao_Paulo] PHP Fatal error:  Uncaught TypeError: Unsupported operand types: string + null in /home/admin/web/socket.nfxtrade.com/public_html/vendor/arthurkushman/php-wss/src/WebSocketServer.php:242
Stack trace:
#0 /home/admin/web/socket.nfxtrade.com/public_html/vendor/arthurkushman/php-wss/src/WebSocketServer.php(180): WSSC\WebSocketServer->messagesWorker()
#1 /home/admin/web/socket.nfxtrade.com/public_html/vendor/arthurkushman/php-wss/src/WebSocketServer.php(130): WSSC\WebSocketServer->looping()
#2 /home/admin/web/socket.nfxtrade.com/public_html/vendor/arthurkushman/php-wss/src/WebSocketServer.php(108): WSSC\WebSocketServer->eventLoop()
#3 /home/admin/web/socket.nfxtrade.com/public_html/wstrade.php(24): WSSC\WebSocketServer->run()
#4 {main}
  thrown in /home/admin/web/socket.nfxtrade.com/public_html/vendor/arthurkushman/php-wss/src/WebSocketServer.php on line 242
```
  
Over and over again the websocket connection is reset and this error is thrown in the log, I couldn't find anything I'm sending that could be the culprit, but I'm imagining the modification below can work around it.

```
   if ($data === false) { // payload is too large - waiting for remained data
        $largePayloadData += ($dataPayload ?? '0');
   }
```

**Comment by arthurkushman** [comment]
Hi @jeankassio, thank u for reporting this bug - fixed

https://github.com/arthurkushman/php-wss/releases/tag/2.0.5

**Comment by arthurkushman** [comment]
@jeankassio r u ok with this?

**Comment by jeankassio** [comment]
Cool, thank you so much for the correction so fast
