### ISSUE TITLE
PHP Fatal error:  Uncaught WSSC\Exceptions\ConnectionException: Could not open socket to "localhost:8888":  (0).

### ISSUE THREAD

**Issue by sumonst21** [arthurkushman/php-wss#72]
Hi @arthurkushman , 
Can you help why I'm seeing this error when trying wss with valid ssl certs? but working fine on ws. 
```bash
[root@testing9920 wss]# php public/test.php
PHP Fatal error:  Uncaught WSSC\Exceptions\ConnectionException: Could not open socket to "localhost:8888":  (0). in /home/wss/vendor/arthurkushman/php-wss/src/Components/WscMain.php:109
Stack trace:
#0 /home/wss/vendor/arthurkushman/php-wss/src/WebSocketClient.php(23): WSSC\Components\WscMain->connect()                                                                          
#1 /home/wss/public/test.php(5): WSSC\WebSocketClient->__construct()
#2 {main}
  thrown in /home/wss/vendor/arthurkushman/php-wss/src/Components/WscMain.php on line 109
```
```php
require_once 'handler.class.php';
use WSSC\WebSocketServer;
use WSSCTEST\ServerHandler;
use WSSC\Components\ServerConfig;
$config = new ServerConfig();
$config->setClientsPerFork(2500);
$config->setStreamSelectTimeout(2 * 3600);
$config->setIsSsl(true)->setAllowSelfSigned(true)
    ->setCryptoType(STREAM_CRYPTO_METHOD_SSLv23_SERVER)
    ->setLocalCert("/etc/letsencrypt/live/wss.xyz/cert.pem")->setLocalPk("/etc/letsencrypt/live/wss.xyz/privkey.pem")
    ->setPort(8888);
$webSocketServer = new WebSocketServer(new ServerHandler(), $config);
$webSocketServer->run();
```
test.php
```php
require_once 'handler.class.php';
use WSSC\WebSocketClient;
use \WSSC\Components\ClientConfig;
$client = new WebSocketClient('ws://localhost:8000/notifications/messanger/yourtoken123', new ClientConfig());
$client->send('{"user_id" : 123}');
echo $client->receive();
```
works fine without ssl:
```bash
[root@testing9920 wss]# php public/test.php
{"user_id" : 123}
```

**Comment by sumonst21** [comment]
Ok It worked, 
I had to set setAllowSelfSigned to false. 
the config that worked: 
```php
require_once 'handler.class.php';
use WSSC\WebSocketServer;
use WSSCTEST\ServerHandler;
use WSSC\Components\ServerConfig;
$config = new ServerConfig();
$config->setClientsPerFork(2500);
$config->setStreamSelectTimeout(2 * 3600);
$config->setIsSsl(true)->setAllowSelfSigned(false)
    ->setCryptoType(STREAM_CRYPTO_METHOD_SSLv23_SERVER)
    ->setLocalCert("/etc/letsencrypt/live/wss.xyz/cert.pem")->setLocalPk("/etc/letsencrypt/live/wss.xyz/privkey.pem")
    ->setPort(8888);
$webSocketServer = new WebSocketServer(new ServerHandler(), $config);
$webSocketServer->run();
```
test.php
```php
require_once 'handler.class.php';
use WSSC\WebSocketClient;
use \WSSC\Components\ClientConfig;
$config = new ClientConfig();
$config->setContextOptions(['ssl' => ['verify_peer' => false, 'verify_peer_name' => false]]);
$client = new WebSocketClient('wss://localhost:8888/notifications/messanger/yourtoken123', $config);
$client->send('{"user_id" : 123}');
echo $client->receive();
```
